spring:
  profiles:
    active: dev # 激活开发环境配置

---

server:
  port: 9001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.mengxuegu.springcloud.entities  # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件

spring:
  profiles: dev
  application:
    name: dream-product-dev-bus #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/sys?serverTimezone=GMT%2B8  # 数据库名称
    username: root
    password: suyw
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl: # 客户端(服务提供者)注册到哪一个Eureka Server服务注册中心，多个用逗号分隔
      defaultZone: http://dream.com:6003/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}    # 指定实例ID,就不会显示主机名了
    preferIpAddress: true #访问路径可以显示IP地址
    
--- 
 
server:
  port: 9002

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.mengxuegu.springcloud.entities  # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件

spring:
  profiles: prod
  application:
    name: dream-product #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/sys?serverTimezone=GMT%2B8  # 数据库名称
    username: root
    password: suyw
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl: # 客户端(服务提供者)注册到哪一个Eureka Server服务注册中心，多个用逗号分隔
      defaultZone: http://dream.com:6003/eureka,http://free.com:6004/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}    # 指定实例ID,就不会显示主机名了
    preferIpAddress: true #访问路径可以显示IP地址



